name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ubuntu-latest-cargo-build-wasm-stable-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - name: Build wasm
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --no-default-features --target wasm32-unknown-unknown
      - name: Bind wasm
        uses: jetli/wasm-bindgen-action@v0.1.0
        with:
          args: --out-dir target --target web assets/wordlrs.wasm
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          force_orphan: true
          keep_files: true
